import re, os

path = '/home/user/defense-dashboard/script.js'
with open(path, encoding='utf-8') as f:
    content = f.read()

NEW = """,
    { id:'c18', name:'SAIC', logo:'https://logo.clearbit.com/saic.com', country:'US', ticker:'SAIC', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:7.4, specialization:'Defense IT / Intelligence', website:'https://www.saic.com/', ir:'https://investors.saic.com/', linkedin:'https://www.linkedin.com/company/saic/', x:'https://x.com/SAIC_Inc', description:'Defense IT and intelligence services contractor for US government and military.', listed:true },
    { id:'c19', name:'Booz Allen Hamilton', logo:'https://logo.clearbit.com/boozallen.com', country:'US', ticker:'BAH', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:10.7, specialization:'Defense IT / Consulting', website:'https://www.boozallen.com/', ir:'https://ir.boozallen.com/', linkedin:'https://www.linkedin.com/company/booz-allen-hamilton/', x:'https://x.com/BoozAllen', description:'Defense and intelligence consulting and analytics firm.', listed:true },
    { id:'c20', name:'Kratos Defense', logo:'https://logo.clearbit.com/kratosdefense.com', country:'US', ticker:'KTOS', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:1.1, specialization:'Drones / Satellites / Defense Tech', website:'https://www.kratosdefense.com/', ir:'https://ir.kratosdefense.com/', linkedin:'https://www.linkedin.com/company/kratos-defense-and-security-solutions/', x:'https://x.com/KratosDefense', description:'Drone, satellite and high-speed tactical systems developer.', listed:true },
    { id:'c21', name:'Mercury Systems', logo:'https://logo.clearbit.com/mrcy.com', country:'US', ticker:'MRCY', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:0.9, specialization:'Defense Electronics / Processing', website:'https://www.mrcy.com/', ir:'https://investors.mrcy.com/', linkedin:'https://www.linkedin.com/company/mercury-systems/', x:'', description:'Mission-critical processing and electronics for defense platforms.', listed:true },
    { id:'c22', name:'Curtiss-Wright', logo:'https://logo.clearbit.com/curtisswright.com', country:'US', ticker:'CW', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:3.1, specialization:'Defense Electronics / Naval', website:'https://www.curtisswright.com/', ir:'https://investors.curtisswright.com/', linkedin:'https://www.linkedin.com/company/curtiss-wright/', x:'', description:'Defense electronics and controls for naval and aerospace platforms.', listed:true },
    { id:'c23', name:'Moog Inc', logo:'https://logo.clearbit.com/moog.com', country:'US', ticker:'MOG.A', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:3.4, specialization:'Precision Motion / Actuation', website:'https://www.moog.com/', ir:'https://ir.moog.com/', linkedin:'https://www.linkedin.com/company/moog/', x:'', description:'Precision motion control for defense aircraft, missiles and naval systems.', listed:true },
    { id:'c24', name:'Textron', logo:'https://logo.clearbit.com/textron.com', country:'US', ticker:'TXT', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:13.7, specialization:'Helicopters / Aircraft / Ground Vehicles', website:'https://www.textron.com/', ir:'https://investors.textron.com/', linkedin:'https://www.linkedin.com/company/textron/', x:'https://x.com/Textron', description:'Bell helicopters, military aircraft and armored vehicles manufacturer.', listed:true },
    { id:'c25', name:'Teledyne Technologies', logo:'https://logo.clearbit.com/teledyne.com', country:'US', ticker:'TDY', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:5.6, specialization:'Defense Sensors / Imaging', website:'https://www.teledyne.com/', ir:'https://www.teledyne.com/en-us/investor-relations/', linkedin:'https://www.linkedin.com/company/teledyne-technologies/', x:'', description:'Sensors, imaging and instrumentation for defense and space.', listed:true },
    { id:'c26', name:'AeroVironment', logo:'https://logo.clearbit.com/avinc.com', country:'US', ticker:'AVAV', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:0.7, specialization:'UAS / Loitering Munitions', website:'https://www.avinc.com/', ir:'https://ir.avinc.com/', linkedin:'https://www.linkedin.com/company/aerovironment/', x:'https://x.com/AeroVironment', description:'Tactical drones and loitering munitions for US Army and allies.', listed:true },
    { id:'c27', name:'Parsons Corporation', logo:'https://logo.clearbit.com/parsons.com', country:'US', ticker:'PSN', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:6.1, specialization:'Defense IT / Infrastructure', website:'https://www.parsons.com/', ir:'https://investors.parsons.com/', linkedin:'https://www.linkedin.com/company/parsons-corporation/', x:'https://x.com/ParsonsCorp', description:'Federal defense IT, cyber and critical infrastructure engineering.', listed:true },
    { id:'c28', name:'Leonardo DRS', logo:'https://logo.clearbit.com/leonardodrs.com', country:'US', ticker:'DRS', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:2.6, specialization:'Defense Electronics / Ground Systems', website:'https://www.leonardodrs.com/', ir:'https://ir.leonardodrs.com/', linkedin:'https://www.linkedin.com/company/leonardo-drs/', x:'', description:'Defense electronics and ground vehicle systems for US DoD.', listed:true },
    { id:'c29', name:'CACI International', logo:'https://logo.clearbit.com/caci.com', country:'US', ticker:'CACI', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:7.1, specialization:'Defense IT / Intelligence', website:'https://www.caci.com/', ir:'https://investor.caci.com/', linkedin:'https://www.linkedin.com/company/caci-international/', x:'https://x.com/CACIIntl', description:'IT solutions and services for defense and intelligence community.', listed:true },
    { id:'c30', name:'BWX Technologies', logo:'https://logo.clearbit.com/bwxt.com', country:'US', ticker:'BWXT', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:2.8, specialization:'Nuclear Defense / Naval Reactors', website:'https://www.bwxt.com/', ir:'https://investors.bwxt.com/', linkedin:'https://www.linkedin.com/company/bwx-technologies/', x:'', description:'Nuclear components and reactors for US Navy submarines.', listed:true },
    { id:'c31', name:'Palantir Technologies', logo:'https://logo.clearbit.com/palantir.com', country:'US', ticker:'PLTR', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:2.9, specialization:'Defense AI / Data Analytics', website:'https://www.palantir.com/', ir:'https://investors.palantir.com/', linkedin:'https://www.linkedin.com/company/palantir-technologies/', x:'https://x.com/PalantirTech', description:'AI-powered analytics platforms for defense and intelligence agencies.', listed:true },
    { id:'c32', name:'Rocket Lab USA', logo:'https://logo.clearbit.com/rocketlabusa.com', country:'US', ticker:'RKLB', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:0.4, specialization:'Space Launch / Defense Satellites', website:'https://www.rocketlabusa.com/', ir:'https://investors.rocketlabusa.com/', linkedin:'https://www.linkedin.com/company/rocket-lab/', x:'https://x.com/RocketLab', description:'Small satellite launch vehicles and spacecraft for defense missions.', listed:true },
    { id:'c33', name:'Axon Enterprise', logo:'https://logo.clearbit.com/axon.com', country:'US', ticker:'AXON', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:2.0, specialization:'Public Safety Technology', website:'https://www.axon.com/', ir:'https://investor.axon.com/', linkedin:'https://www.linkedin.com/company/axon-enterprise/', x:'https://x.com/axon_us', description:'Tasers, body cameras and cloud software for law enforcement.', listed:true },
    { id:'c34', name:'Amentum Holdings', logo:'https://logo.clearbit.com/amentum.com', country:'US', ticker:'AMTM', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:13.0, specialization:'Defense Services / Government', website:'https://www.amentum.com/', ir:'https://investors.amentum.com/', linkedin:'https://www.linkedin.com/company/amentum/', x:'', description:'Global defense and government services contractor.', listed:true },
    { id:'c35', name:'KBR Inc', logo:'https://logo.clearbit.com/kbr.com', country:'US', ticker:'KBR', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:7.5, specialization:'Defense Engineering / Services', website:'https://www.kbr.com/', ir:'https://investors.kbr.com/', linkedin:'https://www.linkedin.com/company/kbr-inc/', x:'https://x.com/KBRInc', description:'Defense engineering, logistics and sustainment services worldwide.', listed:true },
    { id:'c36', name:'OSI Systems', logo:'https://logo.clearbit.com/osi-systems.com', country:'US', ticker:'OSIS', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:1.4, specialization:'Security Electronics / Detection', website:'https://www.osi-systems.com/', ir:'https://investors.osi-systems.com/', linkedin:'https://www.linkedin.com/company/osi-systems/', x:'', description:'Security inspection and optoelectronics for defense and border security.', listed:true },
    { id:'c37', name:'BigBear.ai', logo:'https://logo.clearbit.com/bigbear.ai', country:'US', ticker:'BBAI', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:0.2, specialization:'Defense AI / Analytics', website:'https://bigbear.ai/', ir:'https://ir.bigbear.ai/', linkedin:'https://www.linkedin.com/company/bigbear-ai/', x:'https://x.com/BigBear_ai', description:'AI decision intelligence for defense and intelligence missions.', listed:true },
    { id:'c38', name:'Olin Corporation', logo:'https://logo.clearbit.com/olin.com', country:'US', ticker:'OLN', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:7.0, specialization:'Ammunition / Defense Chemicals', website:'https://www.olin.com/', ir:'https://investors.olin.com/', linkedin:'https://www.linkedin.com/company/olin-corporation/', x:'', description:'Winchester ammunition and defense chemicals manufacturer.', listed:true },
    { id:'c39', name:'Vista Outdoor', logo:'https://logo.clearbit.com/vistaoutdoor.com', country:'US', ticker:'VSTO', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:3.0, specialization:'Ammunition / Outdoor Defense', website:'https://www.vistaoutdoor.com/', ir:'https://investors.vistaoutdoor.com/', linkedin:'https://www.linkedin.com/company/vista-outdoor/', x:'', description:'Federal, CCI and Speer ammunition brands for military and law enforcement.', listed:true },
    { id:'c40', name:'Sturm Ruger', logo:'https://logo.clearbit.com/ruger.com', country:'US', ticker:'RGR', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:0.5, specialization:'Firearms', website:'https://www.ruger.com/', ir:'https://www.ruger.com/corporate/html/investor_relations/', linkedin:'https://www.linkedin.com/company/ruger/', x:'', description:'American firearms manufacturer for civilian, law enforcement and military markets.', listed:true },
    { id:'c41', name:'Smith & Wesson Brands', logo:'https://logo.clearbit.com/smith-wesson.com', country:'US', ticker:'SWBI', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:0.3, specialization:'Firearms', website:'https://www.smith-wesson.com/', ir:'https://ir.aob.com/', linkedin:'https://www.linkedin.com/company/smith-wesson/', x:'', description:'Iconic American handgun and rifle manufacturer.', listed:true },
    { id:'c42', name:'Hexcel Corporation', logo:'https://logo.clearbit.com/hexcel.com', country:'US', ticker:'HXL', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:1.8, specialization:'Aerospace Composites / Defense Materials', website:'https://www.hexcel.com/', ir:'https://investors.hexcel.com/', linkedin:'https://www.linkedin.com/company/hexcel/', x:'', description:'Advanced composite materials for fighter jets and defense structures.', listed:true },
    { id:'c43', name:'VSE Corporation', logo:'https://logo.clearbit.com/vsecorp.com', country:'US', ticker:'VSE', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:1.9, specialization:'Defense MRO / Logistics', website:'https://www.vsecorp.com/', ir:'https://investors.vsecorp.com/', linkedin:'https://www.linkedin.com/company/vse-corporation/', x:'', description:'Aviation and defense MRO, supply chain and logistics services.', listed:true },
    { id:'c44', name:'Viasat', logo:'https://logo.clearbit.com/viasat.com', country:'US', ticker:'VSAT', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:4.5, specialization:'Defense Satellite Communications', website:'https://www.viasat.com/', ir:'https://investors.viasat.com/', linkedin:'https://www.linkedin.com/company/viasat/', x:'https://x.com/ViaSat', description:'Military satellite communications and tactical data links.', listed:true },
    { id:'c45', name:'ICF International', logo:'https://logo.clearbit.com/icf.com', country:'US', ticker:'ICFI', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:2.0, specialization:'Defense Consulting / IT', website:'https://www.icf.com/', ir:'https://investor.icf.com/', linkedin:'https://www.linkedin.com/company/icf/', x:'', description:'Management consulting and technology services for US defense and federal agencies.', listed:true },
    { id:'c46', name:'QinetiQ Group', logo:'https://logo.clearbit.com/qinetiq.com', country:'GB', ticker:'QQ.', yf_ticker:'QQ.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:2.1, specialization:'Defense R&D / Test and Evaluation', website:'https://www.qinetiq.com/', ir:'https://www.qinetiq.com/en/investors', linkedin:'https://www.linkedin.com/company/qinetiq/', x:'https://x.com/QinetiQ', description:'Defense technology research and test and evaluation services for UK MoD and allies.', listed:true },
    { id:'c47', name:'Chemring Group', logo:'https://logo.clearbit.com/chemring.co.uk', country:'GB', ticker:'CHG', yf_ticker:'CHG.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:0.67, specialization:'Munitions / Countermeasures / CBRN', website:'https://www.chemring.co.uk/', ir:'https://www.chemring.co.uk/investors', linkedin:'https://www.linkedin.com/company/chemring-group/', x:'', description:'Munitions, countermeasures and CBRN detection systems for NATO forces.', listed:true },
    { id:'c48', name:'Babcock International', logo:'https://logo.clearbit.com/babcock.co.uk', country:'GB', ticker:'BAB', yf_ticker:'BAB.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:4.6, specialization:'Naval / Nuclear Services', website:'https://www.babcock.co.uk/', ir:'https://investors.babcockinternational.com/', linkedin:'https://www.linkedin.com/company/babcock-international-group/', x:'https://x.com/BabcockIntl', description:'Naval and nuclear support services for UK Royal Navy.', listed:true },
    { id:'c49', name:'Rolls-Royce Holdings', logo:'https://logo.clearbit.com/rolls-royce.com', country:'GB', ticker:'RR.', yf_ticker:'RR.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:17.9, specialization:'Defense Jet Engines / Naval Propulsion', website:'https://www.rolls-royce.com/', ir:'https://www.rolls-royce.com/investors/', linkedin:'https://www.linkedin.com/company/rolls-royce/', x:'https://x.com/rollsroyce', description:'Military jet engines and naval nuclear propulsion systems.', listed:true },
    { id:'c50', name:'Melrose Industries', logo:'https://logo.clearbit.com/melroseplc.net', country:'GB', ticker:'MRO', yf_ticker:'MRO.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:3.0, specialization:'Aerospace Structures / Defense Components', website:'https://www.melroseplc.net/', ir:'https://www.melroseplc.net/investors/', linkedin:'https://www.linkedin.com/company/melrose-industries/', x:'', description:'GKN Aerospace structures and defense components manufacturer.', listed:true },
    { id:'c51', name:'Avon Protection', logo:'https://logo.clearbit.com/avon-protection.com', country:'GB', ticker:'AVON', yf_ticker:'AVON.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:0.1, specialization:'CBRN Protection / Ballistics', website:'https://www.avon-protection.com/', ir:'https://www.avon-protection.com/investors/', linkedin:'https://www.linkedin.com/company/avon-protection/', x:'', description:'CBRN respirators and body armor for military and first responders.', listed:true },
    { id:'c52', name:'Serco Group', logo:'https://logo.clearbit.com/serco.com', country:'GB', ticker:'SRP', yf_ticker:'SRP.L', exchange:'LSE', price:0, change:0, marketCap:0, currency:'GBP', revenue:4.5, specialization:'Defense Services / Government', website:'https://www.serco.com/', ir:'https://www.serco.com/investors/', linkedin:'https://www.linkedin.com/company/serco/', x:'https://x.com/Serco_Group', description:'Defense and government services including base operations worldwide.', listed:true },
    { id:'c53', name:'Safran', logo:'https://logo.clearbit.com/safran-group.com', country:'FR', ticker:'SAF', yf_ticker:'SAF.PA', exchange:'Euronext Paris', price:0, change:0, marketCap:0, currency:'EUR', revenue:27.0, specialization:'Propulsion / Avionics / Navigation', website:'https://www.safran-group.com/', ir:'https://www.safran-group.com/investors', linkedin:'https://www.linkedin.com/company/safran/', x:'https://x.com/Safran', description:'Aircraft engines, navigation systems and defense electronics for military aviation.', listed:true },
    { id:'c54', name:'Airbus', logo:'https://logo.clearbit.com/airbus.com', country:'FR', ticker:'AIR', yf_ticker:'AIR.PA', exchange:'Euronext Paris', price:0, change:0, marketCap:0, currency:'EUR', revenue:69.0, specialization:'Military Aircraft / Space / Helicopters', website:'https://www.airbus.com/', ir:'https://www.airbus.com/en/investors', linkedin:'https://www.linkedin.com/company/airbus/', x:'https://x.com/Airbus', description:'Military transport aircraft, Eurofighter, helicopters and space systems.', listed:true },
    { id:'c55', name:'Dassault Aviation', logo:'https://logo.clearbit.com/dassault-aviation.com', country:'FR', ticker:'AM', yf_ticker:'AM.PA', exchange:'Euronext Paris', price:0, change:0, marketCap:0, currency:'EUR', revenue:7.5, specialization:'Fighter Aircraft', website:'https://www.dassault-aviation.com/', ir:'https://www.dassault-aviation.com/en/finance/', linkedin:'https://www.linkedin.com/company/dassault-aviation/', x:'https://x.com/Dassault_OnAir', description:'Rafale fighter jet manufacturer and Falcon business aviation.', listed:true },
    { id:'c56', name:'Hensoldt AG', logo:'https://logo.clearbit.com/hensoldt.net', country:'DE', ticker:'HAG', yf_ticker:'HAG.DE', exchange:'Xetra', price:0, change:0, marketCap:0, currency:'EUR', revenue:2.3, specialization:'Defense Sensors / Radar / Optronics', website:'https://www.hensoldt.net/', ir:'https://www.hensoldt.net/investors/', linkedin:'https://www.linkedin.com/company/hensoldt/', x:'https://x.com/HENSOLDT', description:'Radar, optronics and electronic warfare sensors for Bundeswehr and export.', listed:true },
    { id:'c57', name:'MTU Aero Engines', logo:'https://logo.clearbit.com/mtu.de', country:'DE', ticker:'MTX', yf_ticker:'MTX.DE', exchange:'Xetra', price:0, change:0, marketCap:0, currency:'EUR', revenue:7.5, specialization:'Defense Jet Engines / MRO', website:'https://www.mtu.de/', ir:'https://www.mtu.de/investors/', linkedin:'https://www.linkedin.com/company/mtu-aero-engines/', x:'https://x.com/MTUAeroEngines', description:'Military and civil jet engine manufacturer and MRO provider.', listed:true },
    { id:'c58', name:'Fincantieri', logo:'https://logo.clearbit.com/fincantieri.com', country:'IT', ticker:'FNC', yf_ticker:'FNC.MI', exchange:'Borsa Italiana', price:0, change:0, marketCap:0, currency:'EUR', revenue:8.5, specialization:'Naval Shipbuilding', website:'https://www.fincantieri.com/', ir:'https://www.fincantieri.com/en/investors/', linkedin:'https://www.linkedin.com/company/fincantieri/', x:'https://x.com/fincantieri', description:'Italian naval shipbuilder producing frigates, destroyers and submarines.', listed:true },
    { id:'c59', name:'Avio SpA', logo:'https://logo.clearbit.com/avio.com', country:'IT', ticker:'AV', yf_ticker:'AV.MI', exchange:'Borsa Italiana', price:0, change:0, marketCap:0, currency:'EUR', revenue:0.5, specialization:'Space Propulsion / Defense Launch', website:'https://www.avio.com/', ir:'https://www.avio.com/en/investors', linkedin:'https://www.linkedin.com/company/avio/', x:'', description:'Vega rocket propulsion and solid rocket motors for defense and space.', listed:true },
    { id:'c60', name:'Indra Sistemas', logo:'https://logo.clearbit.com/indracompany.com', country:'ES', ticker:'IDR', yf_ticker:'IDR.MC', exchange:'BME', price:0, change:0, marketCap:0, currency:'EUR', revenue:4.3, specialization:'Defense Electronics / Air Traffic', website:'https://www.indracompany.com/', ir:'https://www.indracompany.com/en/investors', linkedin:'https://www.linkedin.com/company/indra/', x:'https://x.com/IndraSistemas', description:'Spanish defense electronics, radar and command systems for NATO forces.', listed:true },
    { id:'c61', name:'ASELSAN', logo:'https://logo.clearbit.com/aselsan.com', country:'TR', ticker:'ASELS', yf_ticker:'ASELS.IS', exchange:'Borsa Istanbul', price:0, change:0, marketCap:0, currency:'TRY', revenue:50.0, specialization:'Defense Electronics / Communications', website:'https://www.aselsan.com/', ir:'https://www.aselsan.com/en/investor-relations', linkedin:'https://www.linkedin.com/company/aselsan/', x:'https://x.com/ASELSAN_AS', description:'Turkey largest defense electronics, communications and radar systems company.', listed:true },
    { id:'c62', name:'Elbit Systems', logo:'https://logo.clearbit.com/elbitsystems.com', country:'IL', ticker:'ESLT', exchange:'NASDAQ', price:0, change:0, marketCap:0, currency:'USD', revenue:6.5, specialization:'Defense Electronics / UAVs / Optronics', website:'https://www.elbitsystems.com/', ir:'https://ir.elbitsystems.com/', linkedin:'https://www.linkedin.com/company/elbit-systems/', x:'https://x.com/ElbitSystems', description:'Israeli defense electronics, UAVs, optronics and electronic warfare systems.', listed:true },
    { id:'c63', name:'Hanwha Aerospace', logo:'https://logo.clearbit.com/hanwha.com', country:'KR', ticker:'HNWHA', yf_ticker:'272210.KS', exchange:'KRX', price:0, change:0, marketCap:0, currency:'KRW', revenue:10000.0, specialization:'Aerospace Engines / Artillery / UAVs', website:'https://www.hanwhaaerospace.com/', ir:'https://www.hanwhaaerospace.com/', linkedin:'https://www.linkedin.com/company/hanwha-aerospace/', x:'', description:'South Korean aerospace engines, K9 artillery systems and drone manufacturer.', listed:true },
    { id:'c64', name:'LIG Nex1', logo:'https://logo.clearbit.com/lignex1.com', country:'KR', ticker:'LIGNEX1', yf_ticker:'015570.KS', exchange:'KRX', price:0, change:0, marketCap:0, currency:'KRW', revenue:2300.0, specialization:'Guided Weapons / Missiles / EW', website:'https://www.lignex1.com/', ir:'https://www.lignex1.com/', linkedin:'https://www.linkedin.com/company/lignex1/', x:'', description:'South Korean guided weapons, missiles and electronic warfare systems.', listed:true },
    { id:'c65', name:'Korea Aerospace Industries', logo:'https://logo.clearbit.com/koreaaero.com', country:'KR', ticker:'KAI', yf_ticker:'047810.KS', exchange:'KRX', price:0, change:0, marketCap:0, currency:'KRW', revenue:4200.0, specialization:'Military Aircraft / Helicopters', website:'https://www.koreaaero.com/', ir:'https://www.koreaaero.com/', linkedin:'https://www.linkedin.com/company/korea-aerospace-industries-ltd/', x:'', description:'T-50 trainer jet, FA-50 light fighter and KF-21 next-generation fighter developer.', listed:true },
    { id:'c66', name:'Hanwha Systems', logo:'https://logo.clearbit.com/hanwha.com', country:'KR', ticker:'HWASYS', yf_ticker:'267260.KS', exchange:'KRX', price:0, change:0, marketCap:0, currency:'KRW', revenue:2600.0, specialization:'Defense Electronics / Radar / Satellites', website:'https://www.hanwhasystems.com/', ir:'https://www.hanwhasystems.com/', linkedin:'https://www.linkedin.com/company/hanwha-systems/', x:'', description:'South Korean defense electronics, AESA radar and reconnaissance satellites.', listed:true },
    { id:'c67', name:'Hyundai Rotem', logo:'https://logo.clearbit.com/hyundai-rotem.co.kr', country:'KR', ticker:'HROTEM', yf_ticker:'064350.KS', exchange:'KRX', price:0, change:0, marketCap:0, currency:'KRW', revenue:4600.0, specialization:'Armored Vehicles / Trains', website:'https://www.hyundai-rotem.co.kr/', ir:'https://www.hyundai-rotem.co.kr/', linkedin:'https://www.linkedin.com/company/hyundai-rotem/', x:'', description:'K2 Black Panther main battle tank and armored vehicle manufacturer.', listed:true },
    { id:'c68', name:'Mitsubishi Heavy Industries', logo:'https://logo.clearbit.com/mhi.com', country:'JP', ticker:'MHI', yf_ticker:'7011.T', exchange:'TSE', price:0, change:0, marketCap:0, currency:'JPY', revenue:5000.0, specialization:'Naval / Aerospace / Defense Systems', website:'https://www.mhi.com/', ir:'https://www.mhi.com/finance/', linkedin:'https://www.linkedin.com/company/mitsubishi-heavy-industries/', x:'https://x.com/MHI_Group', description:'Japanese defense prime for warships, fighter jets and missile defense systems.', listed:true },
    { id:'c69', name:'Kawasaki Heavy Industries', logo:'https://logo.clearbit.com/khi.co.jp', country:'JP', ticker:'KHI', yf_ticker:'7012.T', exchange:'TSE', price:0, change:0, marketCap:0, currency:'JPY', revenue:2000.0, specialization:'Naval / Submarines / Aerospace', website:'https://www.khi.co.jp/', ir:'https://www.khi.co.jp/ir/', linkedin:'https://www.linkedin.com/company/kawasaki-heavy-industries/', x:'', description:'Submarines, P-1 maritime patrol aircraft and military helicopters for JSDF.', listed:true },
    { id:'c70', name:'IHI Corporation', logo:'https://logo.clearbit.com/ihi.co.jp', country:'JP', ticker:'IHI', yf_ticker:'7013.T', exchange:'TSE', price:0, change:0, marketCap:0, currency:'JPY', revenue:1800.0, specialization:'Defense Engines / Space / Structures', website:'https://www.ihi.co.jp/', ir:'https://www.ihi.co.jp/ir/', linkedin:'https://www.linkedin.com/company/ihi-corporation/', x:'', description:'Jet engines, rocket propulsion and aerostructures for Japan defense and space.', listed:true },
    { id:'c71', name:'NEC Corporation', logo:'https://logo.clearbit.com/nec.com', country:'JP', ticker:'NEC', yf_ticker:'6701.T', exchange:'TSE', price:0, change:0, marketCap:0, currency:'JPY', revenue:3400.0, specialization:'Defense IT / C4ISR / Communications', website:'https://www.nec.com/', ir:'https://www.nec.com/en/investor/', linkedin:'https://www.linkedin.com/company/nec/', x:'https://x.com/NEC_Corporation', description:'C4ISR systems, defense communications and AI surveillance for JSDF.', listed:true },
    { id:'c72', name:'Mitsubishi Electric', logo:'https://logo.clearbit.com/mitsubishielectric.com', country:'JP', ticker:'MELEC', yf_ticker:'6503.T', exchange:'TSE', price:0, change:0, marketCap:0, currency:'JPY', revenue:5000.0, specialization:'Defense Electronics / Radar / Satellites', website:'https://www.mitsubishielectric.com/', ir:'https://www.mitsubishielectric.com/ir/', linkedin:'https://www.linkedin.com/company/mitsubishi-electric/', x:'', description:'Radar systems, missile guidance electronics and defense satellites for JSDF.', listed:true },
    { id:'c73', name:'Hindustan Aeronautics', logo:'https://logo.clearbit.com/hal-india.co.in', country:'IN', ticker:'HAL', yf_ticker:'HAL.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:350.0, specialization:'Military Aircraft / Helicopters', website:'https://hal-india.co.in/', ir:'https://hal-india.co.in/investor-relations', linkedin:'https://www.linkedin.com/company/hal-hindustan-aeronautics-limited/', x:'', description:'India state-owned manufacturer of Tejas fighter jets and Dhruv helicopters.', listed:true },
    { id:'c74', name:'Bharat Electronics', logo:'https://logo.clearbit.com/bel-india.in', country:'IN', ticker:'BEL', yf_ticker:'BEL.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:200.0, specialization:'Defense Electronics / Radar', website:'https://bel-india.in/', ir:'https://bel-india.in/investor-relations/', linkedin:'https://www.linkedin.com/company/bharat-electronics-limited/', x:'', description:'Defense electronics, radar and communication systems for Indian armed forces.', listed:true },
    { id:'c75', name:'Bharat Dynamics', logo:'https://logo.clearbit.com/bdl-india.in', country:'IN', ticker:'BDL', yf_ticker:'BDL.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:100.0, specialization:'Guided Missiles / Torpedoes', website:'https://bdl-india.in/', ir:'https://bdl-india.in/investor-relation/', linkedin:'https://www.linkedin.com/company/bharat-dynamics-limited/', x:'', description:'Surface-to-air missiles, anti-tank missiles and aerial targets for Indian forces.', listed:true },
    { id:'c76', name:'Mazagon Dock', logo:'https://logo.clearbit.com/mazagondock.in', country:'IN', ticker:'MAZDOCK', yf_ticker:'MAZDOCK.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:110.0, specialization:'Naval Shipbuilding / Submarines', website:'https://mazagondock.in/', ir:'https://mazagondock.in/investor-relations/', linkedin:'https://www.linkedin.com/company/mazagon-dock-shipbuilders-limited/', x:'', description:'Indian naval shipbuilder for submarines, destroyers and frigates.', listed:true },
    { id:'c77', name:'Garden Reach Shipbuilders', logo:'https://logo.clearbit.com/grse.in', country:'IN', ticker:'GRSE', yf_ticker:'GRSE.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:42.0, specialization:'Naval Vessels / Coast Guard', website:'https://grse.in/', ir:'https://grse.in/investor_relations/', linkedin:'https://www.linkedin.com/company/garden-reach-shipbuilders-engineers-limited/', x:'', description:'Indian shipyard building frigates, corvettes and fast patrol vessels.', listed:true },
    { id:'c78', name:'Cochin Shipyard', logo:'https://logo.clearbit.com/cochinshipyard.com', country:'IN', ticker:'COCHINSHIP', yf_ticker:'COCHINSHIP.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:90.0, specialization:'Naval Shipbuilding / Aircraft Carriers', website:'https://cochinshipyard.com/', ir:'https://cochinshipyard.com/investor-relations/', linkedin:'https://www.linkedin.com/company/cochin-shipyard/', x:'', description:'India largest shipyard, builder of INS Vikrant aircraft carrier.', listed:true },
    { id:'c79', name:'Solar Industries India', logo:'https://logo.clearbit.com/solarindustries.in', country:'IN', ticker:'SOLARIND', yf_ticker:'SOLARIND.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:60.0, specialization:'Explosives / Ammunition / Loitering Munitions', website:'https://www.solarindustries.in/', ir:'https://www.solarindustries.in/investor-relations/', linkedin:'https://www.linkedin.com/company/solar-industries-india/', x:'', description:'Defense explosives, propellants and Nagastra loitering munitions for Indian forces.', listed:true },
    { id:'c80', name:'Data Patterns India', logo:'https://logo.clearbit.com/datapatternsindia.com', country:'IN', ticker:'DATAPATT', yf_ticker:'DATAPATT.NS', exchange:'NSE', price:0, change:0, marketCap:0, currency:'INR', revenue:8.0, specialization:'Defense Electronics / Avionics', website:'https://www.datapatternsindia.com/', ir:'https://www.datapatternsindia.com/investor-relations/', linkedin:'https://www.linkedin.com/company/data-patterns/', x:'', description:'Avionics and defense electronics systems for Indian aerospace programs.', listed:true },
    { id:'c81', name:'Austal Limited', logo:'https://logo.clearbit.com/austal.com', country:'AU', ticker:'ASB', yf_ticker:'ASB.AX', exchange:'ASX', price:0, change:0, marketCap:0, currency:'AUD', revenue:1.5, specialization:'Naval Shipbuilding / Patrol Vessels', website:'https://www.austal.com/', ir:'https://www.austal.com/investors', linkedin:'https://www.linkedin.com/company/austal/', x:'https://x.com/Austal', description:'Australian shipbuilder of US Navy littoral combat ships and patrol vessels.', listed:true },
    { id:'c82', name:'Electro Optic Systems', logo:'https://logo.clearbit.com/eos-aus.com', country:'AU', ticker:'EOS', yf_ticker:'EOS.AX', exchange:'ASX', price:0, change:0, marketCap:0, currency:'AUD', revenue:0.04, specialization:'Directed Energy / Space Tracking', website:'https://www.eos-aus.com/', ir:'https://www.eos-aus.com/investors/', linkedin:'https://www.linkedin.com/company/electro-optic-systems/', x:'', description:'Remote weapon stations, directed energy and space debris tracking systems.', listed:true },
    { id:'c83', name:'CAE Inc', logo:'https://logo.clearbit.com/cae.com', country:'CA', ticker:'CAE', yf_ticker:'CAE.TO', exchange:'TSX', price:0, change:0, marketCap:0, currency:'CAD', revenue:4.3, specialization:'Flight Simulation / Defense Training', website:'https://www.cae.com/', ir:'https://ir.cae.com/', linkedin:'https://www.linkedin.com/company/cae/', x:'https://x.com/CAE_Inc', description:'Flight simulators and military training systems for air forces worldwide.', listed:true },
    { id:'c84', name:'Magellan Aerospace', logo:'https://logo.clearbit.com/magellanaerospace.com', country:'CA', ticker:'MAL', yf_ticker:'MAL.TO', exchange:'TSX', price:0, change:0, marketCap:0, currency:'CAD', revenue:0.4, specialization:'Aerospace Defense Components', website:'https://www.magellanaerospace.com/', ir:'https://www.magellanaerospace.com/investors/', linkedin:'https://www.linkedin.com/company/magellan-aerospace/', x:'', description:'Aerostructures and engine components for military aircraft and missiles.', listed:true },
    { id:'c85', name:'ST Engineering', logo:'https://logo.clearbit.com/stengg.com', country:'SG', ticker:'S63', yf_ticker:'S63.SI', exchange:'SGX', price:0, change:0, marketCap:0, currency:'SGD', revenue:9.9, specialization:'Defense / Aerospace / Smart Systems', website:'https://www.stengg.com/', ir:'https://investor.stengg.com/', linkedin:'https://www.linkedin.com/company/st-engineering/', x:'https://x.com/stengg', description:'Singapore defense and aerospace conglomerate with naval, land and cyber divisions.', listed:true },
    { id:'c86', name:'Embraer', logo:'https://logo.clearbit.com/embraer.com', country:'BR', ticker:'ERJ', exchange:'NYSE', price:0, change:0, marketCap:0, currency:'USD', revenue:4.3, specialization:'Defense Aircraft / Military Transport', website:'https://defense.embraer.com/', ir:'https://ri.embraer.com.br/', linkedin:'https://www.linkedin.com/company/embraer/', x:'https://x.com/Embraer', description:'KC-390 military transport and A-29 Super Tucano defense aircraft manufacturer.', listed:true }"""

# Insert after c17 MBDA line
insert_after = "listed:false }"
idx = content.find(insert_after)
insert_pos = idx + len(insert_after)
new_content = content[:insert_pos] + NEW + content[insert_pos:]
with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)
print("Done. Companies inserted.")
# Count companies
import re
ids = re.findall(r"id:'c(\d+)'", new_content)
print(f"Total companies: {max(int(i) for i in ids)}")
