// Maps each country to the Wikipedia article whose main image best represents
// its military capability (e.g., "Dassault_Rafale" for France, "Saab_JAS_39_Gripen"
// for Sweden). CountryProfileSection fetches the actual image URL at runtime via
// the Wikipedia REST API (CORS-friendly, no auth needed).
const COUNTRY_WIKI_ARTICLE = {
  "United States":  "Lockheed_Martin_F-22_Raptor",
  "China":          "Chengdu_J-20",
  "Russia":         "Sukhoi_Su-57",
  "France":         "Dassault_Rafale",
  "United Kingdom": "Eurofighter_Typhoon",
  "Germany":        "Leopard_2",
  "India":          "Sukhoi/HAL_FGFA",
  "Japan":          "Mitsubishi_F-2",
  "South Korea":    "KAI_KF-21_Boramae",
  "Australia":      "F/A-18F_Super_Hornet",
  "Italy":          "Eurofighter_Typhoon",
  "Israel":         "Lockheed_Martin_F-35_Lightning_II",
  "Turkey":         "Baykar_Bayraktar_TB2",
  "Poland":         "Leopard_2",
  "Ukraine":        "Mi-24",
  "Sweden":         "Saab_JAS_39_Gripen",
  "Norway":         "Lockheed_Martin_F-35_Lightning_II",
  "Greece":         "Dassault_Mirage_2000",
  "Spain":          "Eurofighter_Typhoon",
  "Netherlands":    "Holland-class_frigate",
  "Brazil":         "Embraer_C-390_Millennium",
  "Canada":         "Lockheed_Martin_F-35_Lightning_II",
  "Saudi Arabia":   "McDonnell_Douglas_F-15_Eagle",
  "United Arab Emirates": "General_Dynamics_F-16_Fighting_Falcon",
  "Taiwan":         "General_Dynamics_F-16_Fighting_Falcon",
  "Pakistan":       "Chengdu/CAC_JF-17_Thunder",
  "Egypt":          "Dassault_Rafale",
  "Indonesia":      "Dassault_Rafale",
  "Vietnam":        "Sukhoi_Su-30",
  "Singapore":      "Lockheed_Martin_F-35_Lightning_II",
  "Thailand":       "Saab_JAS_39_Gripen",
  "Malaysia":       "Sukhoi_Su-30",
  "South Africa":   "Denel_Rooivalk",
  "Argentina":      "Argentine_Navy",
  "Chile":          "General_Dynamics_F-16_Fighting_Falcon",
  "Colombia":       "IAI_Kfir",
  "Mexico":         "Mexican_Air_Force",
  "Belgium":        "Lockheed_Martin_F-35_Lightning_II",
  "Finland":        "Lockheed_Martin_F-35_Lightning_II",
  "Denmark":        "Lockheed_Martin_F-35_Lightning_II",
  "Czech Republic": "Saab_JAS_39_Gripen",
  "Romania":        "Romanian_Air_Force",
  "Hungary":        "Saab_JAS_39_Gripen",
  "Portugal":       "General_Dynamics_F-16_Fighting_Falcon",
  "Switzerland":    "Boeing_F/A-18_Hornet",
  "Austria":        "Eurofighter_Typhoon",
  "Qatar":          "Dassault_Rafale",
  "Kuwait":         "Eurofighter_Typhoon",
  "Algeria":        "Sukhoi_Su-30",
  "Morocco":        "General_Dynamics_F-16_Fighting_Falcon",
  "Iran":           "Islamic_Revolutionary_Guard_Corps",
  "Iraq":           "Iraqi_Air_Force",
  "Azerbaijan":     "Baykar_Bayraktar_TB2",
  "Jordan":         "General_Dynamics_F-16_Fighting_Falcon",
  "Bangladesh":     "Mikoyan_MiG-29",
  "Myanmar":        "Myanmar_Armed_Forces",
  "Peru":           "Mikoyan_MiG-29",
  "New Zealand":    "Royal_New_Zealand_Air_Force",
  "Nigeria":        "Nigerian_Air_Force",
  "Philippines":    "Korean_Aerospace_Industries_FA-50",
};

// Returns the Wikipedia article title for the country (used to fetch the banner image).
// Falls back to "Military of {Country}" for unmapped countries.
export function getCountryWikiArticle(countryName) {
  return COUNTRY_WIKI_ARTICLE[countryName]
    || `Military_of_${countryName.replace(/ /g, "_")}`;
}
