// Maps country names to ISO 3166-1 alpha-2 codes for flagcdn.com large-format banners.
// flagcdn.com/w2560/{code}.png is always available and renders beautifully with a dark overlay.
const COUNTRY_BANNER_CODES = {
  "France":         "fr",
  "United States":  "us",
  "United Kingdom": "gb",
  "Germany":        "de",
  "Russia":         "ru",
  "China":          "cn",
  "India":          "in",
  "Japan":          "jp",
  "South Korea":    "kr",
  "Australia":      "au",
  "Italy":          "it",
  "Israel":         "il",
  "Turkey":         "tr",
  "Poland":         "pl",
  "Ukraine":        "ua",
  "Sweden":         "se",
  "Norway":         "no",
  "Greece":         "gr",
  "Spain":          "es",
  "Netherlands":    "nl",
  "Saudi Arabia":   "sa",
  "Brazil":         "br",
  "Canada":         "ca",
  "Taiwan":         "tw",
  "Pakistan":       "pk",
  "Egypt":          "eg",
  "Iran":           "ir",
  "Singapore":      "sg",
  "Finland":        "fi",
  "Denmark":        "dk",
  "Belgium":        "be",
  "Switzerland":    "ch",
  "Austria":        "at",
  "Portugal":       "pt",
  "Czech Republic": "cz",
  "Romania":        "ro",
  "Hungary":        "hu",
  "United Arab Emirates": "ae",
  "Qatar":          "qa",
  "Kuwait":         "kw",
  "Algeria":        "dz",
  "Morocco":        "ma",
  "Thailand":       "th",
  "Malaysia":       "my",
  "Philippines":    "ph",
  "Indonesia":      "id",
  "Vietnam":        "vn",
  "New Zealand":    "nz",
  "South Africa":   "za",
  "Nigeria":        "ng",
  "Argentina":      "ar",
  "Colombia":       "co",
  "Chile":          "cl",
  "Mexico":         "mx",
  "Peru":           "pe",
  "Jordan":         "jo",
  "Iraq":           "iq",
  "Azerbaijan":     "az",
  "Bangladesh":     "bd",
  "Myanmar":        "mm",
};

export function getCountryBanner(countryName) {
  const code = COUNTRY_BANNER_CODES[countryName];
  return code ? `https://flagcdn.com/w2560/${code}.png` : null;
}
