// Maps country names to high-quality Wikimedia Commons military photos.
// Each URL points to a real military parade, flagship weapon system, or head-of-state
// ceremony photo — not a flag. The component falls back to a dark gradient on error.
const WP = "https://commons.wikimedia.org/wiki/Special:FilePath/";

const COUNTRY_HERO_IMAGES = {
  // Major military powers — iconic parade or hardware shots
  "China":          WP + "2015_China_Victory_Day_Parade_(20150903130128).jpg",
  "United States":  WP + "F-22_Raptor_edit1_(cropped).jpg",
  "Russia":         WP + "2014_Moscow_Victory_Day_Parade_33.jpg",
  "France":         WP + "Rafale_-_RIAT_2009_arp.jpg",
  "United Kingdom": WP + "RAF_Typhoon_ZK353_at_RIAT_2017_(cropped).jpg",
  "Germany":        WP + "Leopard_2_A7_in_Augustdorf.jpg",
  "India":          WP + "Republic_Day_Parade_2020_India.jpg",
  "Japan":          WP + "Type_10_MBT_camp_fuji_2012.jpg",
  "South Korea":    WP + "K2_Black_Panther.jpg",
  "Australia":      WP + "HMAS_Hobart_(DDG_39)_2018.jpg",
  "Italy":          WP + "ITS_Cavour_(550)_underway.jpg",
  "Israel":         WP + "F-35I_Adir_of_the_Israeli_Air_Force_(cropped).jpg",
  "Turkey":         WP + "Bayraktar_TB2_TEKNOFEST.jpg",
  "Poland":         WP + "Leopard_2A5_Czolg_ubt.jpg",
  "Ukraine":        WP + "T-64BV_of_the_Ukrainian_Army_2014.jpg",
  "Sweden":         WP + "JAS_39C_Gripen,_Swedish_Air_Force_(cropped).jpg",
  "Norway":         WP + "Norwegian_F-35A_at_Luke_AFB_2019.jpg",
  "Greece":         WP + "Mirage_2000-5_Greek_Air_Force.jpg",
  "Spain":          WP + "Eurofighter_Typhoon_Spanish_Air_Force.jpg",
  "Netherlands":    WP + "HNLMS_De_Ruyter_(F804)_2005.jpg",
  "Brazil":         WP + "Fragata_da_marinha_brasileira_e_fragata_americana.jpg",
  "Canada":         WP + "CF-18_Hornet_Royal_Canadian_Air_Force.jpg",
  "Saudi Arabia":   WP + "Royal_Saudi_Air_Force_F-15S_Strike_Eagle.jpg",
  "United Arab Emirates": WP + "F-16E_UAE_Air_Force.jpg",
  "Taiwan":         WP + "ROCAF_F-16.jpg",
  "Pakistan":       WP + "JF-17_Thunder_Pakistan_Air_Force.jpg",
  "Egypt":          WP + "Egyptian_Air_Force_Rafale_F3R.jpg",
  "Indonesia":      WP + "KRI_John_Lie_(358)_Indonesian_Navy.jpg",
  "Vietnam":        WP + "Su-30MK2_Vietnamese_Air_Force.jpg",
  "Singapore":      WP + "Republic_of_Singapore_Air_Force_F-15SG.jpg",
  "Thailand":       WP + "Royal_Thai_Air_Force_JAS-39_Gripen.jpg",
  "Malaysia":       WP + "Royal_Malaysian_Air_Force_Su-30MKM.jpg",
  "South Africa":   WP + "Rooivalk_attack_helicopter_Farnborough_2010.jpg",
  "Argentina":      WP + "ARA_San_Juan_(S-42)_Argentine_Navy.jpg",
  "Chile":          WP + "Chilean_Air_Force_F-16.jpg",
  "Colombia":       WP + "Kfir_Colombian_Air_Force.jpg",
  "Mexico":         WP + "Mexican_Air_Force_PC-7.jpg",
  "Belgium":        WP + "Belgian_Air_Force_F-16AM.jpg",
  "Finland":        WP + "Finnish_Air_Force_F-18C.jpg",
  "Denmark":        WP + "Royal_Danish_Air_Force_F-16AM.jpg",
  "Czech Republic": WP + "Czech_Air_Force_Gripen_JAS-39C.jpg",
  "Romania":        WP + "Romanian_MiG-21_LanceR.jpg",
  "Hungary":        WP + "Hungarian_Air_Force_JAS-39_Gripen.jpg",
  "Portugal":       WP + "Portuguese_Air_Force_F-16AM.jpg",
  "Switzerland":    WP + "Swiss_Air_Force_F-A_18_Hornet.jpg",
  "Austria":        WP + "Austrian_Air_Force_Eurofighter_Typhoon.jpg",
  "Qatar":          WP + "Qatar_Emiri_Air_Force_Rafale.jpg",
  "Kuwait":         WP + "Kuwait_Air_Force_Eurofighter_Typhoon.jpg",
  "Algeria":        WP + "Algerian_Air_Force_Su-30MKA.jpg",
  "Morocco":        WP + "Royal_Moroccan_Air_Force_F-16C.jpg",
  "Iran":           WP + "Iranian_Army_parade_2012.jpg",
  "Iraq":           WP + "Iraqi_Air_Force_F-16IQ.jpg",
  "Ukraine":        WP + "Ukrainian_Army_T-64BV.jpg",
  "Azerbaijan":     WP + "Azerbaijani_Army_parade_2013.jpg",
  "Jordan":         WP + "Royal_Jordanian_Air_Force_F-16AM.jpg",
  "Bangladesh":     WP + "Bangladesh_Air_Force_MiG-29.jpg",
  "Myanmar":        WP + "Tatmadaw_parade_2013.jpg",
  "Peru":           WP + "Peruvian_Air_Force_MiG-29SE.jpg",
  "New Zealand":    WP + "RNZAF_P-3K_Orion.jpg",
  "Nigeria":        WP + "Nigerian_Air_Force_Alpha_Jet.jpg",
  "Philippines":    WP + "Philippine_Air_Force_FA-50.jpg",
};

export function getCountryBanner(countryName) {
  return COUNTRY_HERO_IMAGES[countryName] || null;
}
